### ISSUE TITLE
Can List but not Download

### ISSUE THREAD

**Issue by kstst** [KoenZomers/RingRecordingDownload#16]
**Describe the bug**
I can list my Devices but can not Download. Throwing error "-list or -deviceid required".  *** Turns out the screen shot examples provided show deviceId (CAPS I) not the required deviceid ( Lowercase i ). Please update the documentation. Possibly add -h command line option for help. Thank You for the nice work.  

**To Reproduce**
Use docs to construct the command linr with -deviceID

**Expected behavior**
Download Files

**Screenshots**

https://github.com/KoenZomers/RingRecordingDownload/blob/master/Screenshots/CommandLineOptions.png

**Versions (please complete the following information):**
- Windows 10/
- RingRecordingDownload: Latest - 3.1.0.0

**Comment by Warfork** [comment]
Same issue here. Using -deviceid corrects it, but it still fails to download anything.

Windows 11
Latest version

```
C:\Users\caine\Desktop\win-x64 (3)>RingRecordingDownload.exe -username <email> -password <password> -deviceid <cameraid> -startdate "04-02-2023"

Ring Recordings Download Tool v3.1.0.0 by Koen Zomers

Connecting to Ring services
Authenticating using provided username and password
Two factor authentication enabled on this account, please enter the Ring token from the e-mail, text message or authenticator app:
<2fa>
Downloading all historical events between Sunday 2 April 2023 00:00:00 and now for Ring device <deviceid>
Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[KoenZomers.Ring.Api.Entities.DoorbotHistoryEvent]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at KoenZomers.Ring.Api.Session.GetDoorbotsHistory(DateTime startDate, Nullable`1 endDate, Nullable`1 doorbotId)
   at KoenZomers.Ring.RecordingDownload.Program.Main(String[] args)
   at KoenZomers.Ring.RecordingDownload.Program.<Main>(String[] args)
```

**Comment by danespinosa** [comment]
Hi everyone, I just recently took over the repo, I just published a couple of new versions. Can you please try them out and let me know if you are still able to repro the issue?
[Version 3.1.1.0](https://github.com/KoenZomers/RingRecordingDownload/releases/tag/3.1.1.0)

**Comment by nabilaws** [comment]
Hi ! 
Still facing similar issue
deviceid is not passed with the download step 

`Downloading all historical events between Saturday 18 May 2024 13:03:48 and Saturday 25 May 2024 13:03:48 for Ring device 43655535
1 item found, downloading to C:\Downloads\
1 - 2024-05-25 11-47-58 (7372871762370503023).mp4... failed (The Ring device with Id 'unknown' could not be found). 
Retrying 2/3.
1 - 2024-05-25 11-47-58 (7372871762370503023).mp4... failed (The Ring device with Id 'unknown' could not be found). Retrying 3/3.`

**Comment by danespinosa** [comment]
@nabilaws the issue you are mentioning it's another, your id device is not specified from what I can see in the logs.
